version: '3.4'

services:
  shelter.api:
    image: ${DOCKER_REGISTRY-}shelterapi
    container_name: Shelter.Api
    build:
      context: .
      dockerfile: src/Shelter.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - shelter-db

  shelter-db:
    image: postgres:latest
    container_name: Shelter.Db
    environment:
      - POSTGRES_DB=shelter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  shelter-idp:
    image: jboss/keycloak:latest
    container_name: Shelter.Identity
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/shelter-realm-export.json
    volumes:
      - ./.containers/identity:/opt/jboss/keycloak/standalone/data
      - ./.files/shelter-realm-export.json:/tmp/shelter-realm-export.json
    ports:
      - 18080:8080

  shelter-seq:
    image: datalust/seq:latest
    container_name: Shelter.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
